#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

ENV_FILE=".env.production"
COMPOSE_FILE="infra/docker/docker-compose.pre-prod.yml"

echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║          Nexploy - Installation          ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BOLD}Checking prerequisites...${NC}"

for cmd in ; do
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "${RED}Error: $cmd is not installed.${NC}"
        exit 1
    fi
done

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: docker compose is not available.${NC}"
    exit 1
fi

echo -e "${GREEN}All prerequisites met.${NC}"
echo ""

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}An existing ${ENV_FILE} file was found.${NC}"
    read -p "Overwrite it? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[yY]$ ]]; then
        echo "Keeping existing ${ENV_FILE}. Skipping to build..."
        echo ""
        SKIP_ENV=true
    fi
fi

if [ "$SKIP_ENV" != "true" ]; then

    echo -e "${BOLD}Generating secrets...${NC}"

    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    BETTER_AUTH_SECRET=$(openssl rand -base64 32)
    ENCRYPTION_KEY=$(openssl rand -hex 32)
    INNGEST_EVENT_KEY=$(openssl rand -hex 16)
    INNGEST_SIGNING_KEY=$(openssl rand -hex 32)

    echo -e "${GREEN}Secrets generated.${NC}"
    echo ""

    echo -e "${BOLD}Configuration${NC}"
    echo ""

    read -p "Your domain (e.g. nexploy.example.com): " DOMAIN
    DOMAIN="${DOMAIN#http://}"
    DOMAIN="${DOMAIN#https://}"
    DOMAIN="${DOMAIN%/}"

    if [ -z "$DOMAIN" ]; then
        echo -e "${RED}Error: Domain is required.${NC}"
        exit 1
    fi

    if [[ "$DOMAIN" == */* ]]; then
        echo -e "${RED}Error: Please enter only the domain (e.g. nexploy.example.com).${NC}"
        exit 1
    fi

    read -p "Email for Let's Encrypt certificates: " LETSENCRYPT_EMAIL

    if [[ ! "$LETSENCRYPT_EMAIL" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]]; then
        echo -e "${RED}Error: A valid email is required for Let's Encrypt.${NC}"
        exit 1
    fi

    TRAEFIK_TEMPLATE="infra/traefik/traefik.pre-prod.yml"
    TRAEFIK_GENERATED="infra/traefik/traefik.pre-prod.generated.yml"
    TRAEFIK_STATIC_CONFIG="../traefik/traefik.pre-prod.generated.yml"

    sed "s|email: .*|email: ${LETSENCRYPT_EMAIL}|" "$TRAEFIK_TEMPLATE" > "$TRAEFIK_GENERATED"

    echo -e "${GREEN}Traefik config generated (${TRAEFIK_GENERATED}).${NC}"
    echo ""

    cat > "$ENV_FILE" <<EOF
# =============================================================================
# Nexploy - Production Environment
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# =============================================================================

DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
TRAEFIK_STATIC_CONFIG=${TRAEFIK_STATIC_CONFIG}

POSTGRES_DB=nexploy
POSTGRES_USER=nexploy
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=https://${DOMAIN}

ENCRYPTION_KEY=${ENCRYPTION_KEY}

LOG_LEVEL=info

INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
EOF

    echo -e "${GREEN}.env file created.${NC}"
    echo ""
fi

echo -e "${BOLD}Building Docker images...${NC}"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build

echo ""
echo -e "${BOLD}Starting services...${NC}"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

echo ""

echo -e "${BOLD}Waiting for services to start...${NC}"

SECONDS=0
while [ "$SECONDS" -lt 120 ]; do
    if docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps nexploy 2>/dev/null | grep -q "Up"; then
        break
    fi
    printf "\r  Waiting... (%ss)" "$SECONDS"
    sleep 3
done
echo ""

echo -e "${GREEN}Services started.${NC}"
echo ""

if [ "$SKIP_ENV" = "true" ]; then
    POSTGRES_PASSWORD=$(grep "^POSTGRES_PASSWORD=" "$ENV_FILE" | cut -d'=' -f2-)
    DOMAIN=$(grep "^DOMAIN=" "$ENV_FILE" | cut -d'=' -f2-)
fi

echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║         Installation Complete!           ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Services:${NC}"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo -e "${BOLD}Access:${NC}"
echo -e "  App:       https://${DOMAIN}"
echo ""
echo -e "${BOLD}${YELLOW}PostgreSQL credentials (save these):${NC}"
echo -e "  Database:  nexploy"
echo -e "  User:      nexploy"
echo -e "  Password:  ${BOLD}${POSTGRES_PASSWORD}${NC}"
echo ""
echo -e "${BOLD}Useful commands:${NC}"
echo -e "  Logs:      docker compose -f ${COMPOSE_FILE} --env-file .env logs -f"
echo -e "  Stop:      docker compose -f ${COMPOSE_FILE} --env-file .env stop"
echo -e "  Restart:   docker compose -f ${COMPOSE_FILE} --env-file .env restart"
echo -e "  Teardown:  docker compose -f ${COMPOSE_FILE} --env-file .env down"
echo ""
echo -e "${YELLOW}Make sure your DNS points ${DOMAIN} to this server${NC}"
echo -e "${YELLOW}and that ports 80/443 are open for Traefik + Let's Encrypt.${NC}"
echo ""
