import { z } from 'zod';
import {
    addDomainConfigSchema,
    removeDomainConfigSchema,
    addSslCertificateConfigSchema,
    backupVolumeS3ConfigSchema,
    buildDockerImageConfigSchema,
    cacheRestoreConfigSchema,
    cacheSaveConfigSchema,
    checkContainerLogsConfigSchema,
    cherryPickCommitConfigSchema,
    cloneRepositoryConfigSchema,
    composeFileConfigSchema,
    conditionConfigSchema,
    createContainerConfigSchema,
    createNetworkConfigSchema,
    createReleaseConfigSchema,
    createServiceConfigSchema,
    createVolumeConfigSchema,
    delayConfigSchema,
    deleteContainerConfigSchema,
    deleteImageConfigSchema,
    deleteNetworkConfigSchema,
    deleteVolumeConfigSchema,
    downloadFileConfigSchema,
    fetchSecretsDopplerConfigSchema,
    fetchSecretsVaultConfigSchema,
    gitCloneExtraConfigSchema,
    gitTagConfigSchema,
    httpRequestConfigSchema,
    mergeBranchConfigSchema,
    pruneImagesConfigSchema,
    pullFromRegistryConfigSchema,
    pushToRegistryConfigSchema,
    removeContainerConfigSchema,
    restartContainerConfigSchema,
    runCommandInContainerConfigSchema,
    scaleServiceConfigSchema,
    scanImageConfigSchema,
    sendNotificationConfigSchema,
    setEnvironmentConfigSchema,
    setEnvVarsConfigSchema,
    sonarqubeScanConfigSchema,
    startContainerConfigSchema,
    stopContainerConfigSchema,
    tagImageConfigSchema,
    triggerStageBuildConfigSchema,
    updateCommitStatusConfigSchema,
    updateServiceConfigSchema,
    validateDockerfileConfigSchema,
    waitForHealthConfigSchema,
    waitForPortConfigSchema,
    waitForUrlConfigSchema,
    webhookCloneConfigSchema,
} from '@workspace/schemas-zod/pipeline/nodeConfigs.schema';

export interface NodeMeta {
    schema: z.ZodObject<z.ZodRawShape> | null;
    category: string;
    description: string;
    isStartNode?: boolean;
    isEndNode?: boolean;
    outputs: string[];
    consumesFromUpstream?: string[];
}

export const NODE_META_MAP: Record<string, NodeMeta> = {
    'clone-repository': {
        schema: cloneRepositoryConfigSchema,
        category: 'source',
        description: 'Clones the linked Git repository. Always the first node of a pipeline.',
        isStartNode: true,
        outputs: ['workDir', 'branch', 'commitHash', 'commitMessage'],
    },
    'webhook-clone': {
        schema: webhookCloneConfigSchema,
        category: 'source',
        description: 'Clones the repository when triggered by a webhook push event.',
        isStartNode: true,
        outputs: ['workDir', 'branch', 'commitHash', 'commitMessage'],
    },
    'git-clone-extra': {
        schema: gitCloneExtraConfigSchema,
        category: 'source',
        description: 'Clones a secondary repository (different from the main linked repo).',
        outputs: ['workDir'],
    },
    'build-docker-image': {
        schema: buildDockerImageConfigSchema,
        category: 'build',
        description:
            'Builds a Docker image from a Dockerfile. Use ONLY for Dockerfile-only deployments — do NOT use before deploy-compose (compose handles its own build internally).',
        consumesFromUpstream: ['workDir'],
        outputs: ['imageId', 'imageName'],
    },
    'validate-dockerfile': {
        schema: validateDockerfileConfigSchema,
        category: 'build',
        description: 'Validates Dockerfile syntax without building. Good for CI lint checks.',
        consumesFromUpstream: ['workDir'],
        outputs: [],
    },
    'validate-compose': {
        schema: composeFileConfigSchema,
        category: 'build',
        description: 'Validates a docker-compose file syntax.',
        consumesFromUpstream: ['workDir'],
        outputs: [],
    },
    'push-to-registry': {
        schema: pushToRegistryConfigSchema,
        category: 'build',
        description: 'Pushes a built Docker image to a registry.',
        consumesFromUpstream: ['imageName'],
        outputs: ['pushedImageName'],
    },
    'pull-from-registry': {
        schema: pullFromRegistryConfigSchema,
        category: 'build',
        description: 'Pulls a Docker image from Docker Hub or a private registry.',
        outputs: ['imageName'],
    },
    'tag-image': {
        schema: tagImageConfigSchema,
        category: 'build',
        description: 'Creates a new tag for an existing Docker image.',
        consumesFromUpstream: ['imageId'],
        outputs: ['newImageName'],
    },
    'scan-image': {
        schema: scanImageConfigSchema,
        category: 'build',
        description: 'Scans a Docker image for vulnerabilities using Trivy.',
        consumesFromUpstream: ['imageId'],
        outputs: ['vulnerabilities', 'criticalCount', 'highCount'],
    },
    'sonarqube-scan': {
        schema: sonarqubeScanConfigSchema,
        category: 'build',
        description:
            'Runs a SonarQube code quality analysis. Can fail the pipeline on the quality gate and/or when a metric (e.g. coverage) is below a required minimum score.',
        consumesFromUpstream: ['workDir'],
        outputs: ['qualityGatePassed', 'projectKey', 'score'],
    },
    'deploy-compose': {
        schema: composeFileConfigSchema,
        category: 'deploy',
        description:
            'Deploys a docker-compose stack (runs docker-compose up --build internally — no separate build-docker-image needed). Needs a workDir from an upstream source node. Supports an optional save-version attach-node via its bottom attachment handle.',
        consumesFromUpstream: ['workDir'],
        outputs: [],
    },
    'set-environment': {
        schema: setEnvironmentConfigSchema,
        category: 'deploy',
        description: 'Activates a Nexploy environment for subsequent nodes.',
        outputs: ['environmentId'],
    },
    'create-container': {
        schema: createContainerConfigSchema,
        category: 'deploy',
        description:
            'Creates a Docker container from an image. Chain with start-container to run it.',
        outputs: ['containerId', 'containerName'],
    },
    'start-container': {
        schema: startContainerConfigSchema,
        category: 'deploy',
        description: 'Starts an existing container. Typically placed after create-container.',
        consumesFromUpstream: ['containerId'],
        outputs: ['containerId'],
    },
    'stop-container': {
        schema: stopContainerConfigSchema,
        category: 'deploy',
        description: 'Stops a running container.',
        consumesFromUpstream: ['containerId'],
        outputs: ['containerId'],
    },
    'restart-container': {
        schema: restartContainerConfigSchema,
        category: 'deploy',
        description: 'Restarts a container.',
        consumesFromUpstream: ['containerId'],
        outputs: ['containerId'],
    },
    'remove-container': {
        schema: removeContainerConfigSchema,
        category: 'deploy',
        description: 'Removes a stopped container.',
        consumesFromUpstream: ['containerId'],
        outputs: [],
    },
    'delete-container': {
        schema: deleteContainerConfigSchema,
        category: 'deploy',
        description:
            'Deletes a container, optionally force-removing it even when running and deleting its anonymous volumes.',
        consumesFromUpstream: ['containerId'],
        outputs: [],
    },
    'create-network': {
        schema: createNetworkConfigSchema,
        category: 'deploy',
        description: 'Creates a Docker network.',
        outputs: ['networkId', 'networkName'],
    },
    'create-volume': {
        schema: createVolumeConfigSchema,
        category: 'deploy',
        description: 'Creates a Docker volume.',
        outputs: ['volumeName'],
    },
    'delete-network': {
        schema: deleteNetworkConfigSchema,
        category: 'deploy',
        description: 'Deletes a Docker network.',
        outputs: [],
    },
    'delete-volume': {
        schema: deleteVolumeConfigSchema,
        category: 'deploy',
        description: 'Deletes a Docker volume.',
        outputs: [],
    },
    'add-domain': {
        schema: addDomainConfigSchema,
        category: 'deploy',
        description: 'Adds a custom domain and Traefik routing rule for a container.',
        outputs: ['domain'],
    },
    'remove-domain': {
        schema: removeDomainConfigSchema,
        category: 'deploy',
        description: 'Removes a domain and its Traefik routing rule for the repository.',
        outputs: ['host', 'removed'],
    },
    'add-ssl-certificate': {
        schema: addSslCertificateConfigSchema,
        category: 'deploy',
        description: "Provisions a Let's Encrypt SSL certificate for a domain.",
        outputs: [],
    },
    'create-service': {
        schema: createServiceConfigSchema,
        category: 'deploy',
        description: 'Creates a Docker Swarm service. Requires Swarm mode enabled.',
        outputs: ['serviceId', 'serviceName'],
    },
    'update-service': {
        schema: updateServiceConfigSchema,
        category: 'deploy',
        description: 'Updates an existing Docker Swarm service (rolling update).',
        consumesFromUpstream: ['serviceId'],
        outputs: [],
    },
    'scale-service': {
        schema: scaleServiceConfigSchema,
        category: 'deploy',
        description: 'Scales a Docker Swarm service to a given number of replicas.',
        consumesFromUpstream: ['serviceId'],
        outputs: [],
    },
    'wait-for-health': {
        schema: waitForHealthConfigSchema,
        category: 'flow',
        description: "Waits until a container's health check reports healthy.",
        consumesFromUpstream: ['containerId'],
        outputs: [],
    },
    'wait-for-url': {
        schema: waitForUrlConfigSchema,
        category: 'flow',
        description: 'Polls a URL until it returns the expected HTTP status code.',
        outputs: [],
    },
    'wait-for-port': {
        schema: waitForPortConfigSchema,
        category: 'flow',
        description: 'Waits until a TCP port is open inside a container.',
        consumesFromUpstream: ['containerId'],
        outputs: [],
    },
    delay: {
        schema: delayConfigSchema,
        category: 'flow',
        description: 'Adds a fixed delay (in seconds) between pipeline steps.',
        outputs: [],
    },
    condition: {
        schema: conditionConfigSchema,
        category: 'flow',
        description: 'Logical AND/OR gate — all or any upstream nodes must succeed.',
        outputs: [],
    },
    'run-command-in-container': {
        schema: runCommandInContainerConfigSchema,
        category: 'script',
        description: 'Runs a shell command inside a running container.',
        consumesFromUpstream: ['containerId'],
        outputs: [],
    },
    'env-vars': {
        schema: null,
        category: 'config',
        description: "Injects the repository's environment variables into downstream nodes.",
        outputs: ['vars'],
    },
    'set-env-vars': {
        schema: setEnvVarsConfigSchema,
        category: 'config',
        description: 'Defines inline environment variables for downstream nodes.',
        outputs: [],
    },
    'fetch-secrets-vault': {
        schema: fetchSecretsVaultConfigSchema,
        category: 'config',
        description: 'Fetches secrets from a HashiCorp Vault instance.',
        outputs: ['secrets'],
    },
    'fetch-secrets-doppler': {
        schema: fetchSecretsDopplerConfigSchema,
        category: 'config',
        description: 'Fetches secrets from Doppler.',
        outputs: ['secrets'],
    },
    'clean-workdir': {
        schema: null,
        category: 'utility',
        description:
            'Deletes the cloned repository working directory to free disk space. Should be the LAST node of every pipeline that clones a repository.',
        isEndNode: true,
        consumesFromUpstream: ['workDir'],
        outputs: [],
    },
    'save-version': {
        schema: null,
        category: 'utility',
        description:
            "Records the current build as a version. ATTACH-NODE: connects to the bottom attachment handle of deploy-compose or create-container using sourceHandle:'save-version' and targetHandle:'input'. Never connect it via the regular right output handle.",
        outputs: [],
    },
    'prune-images': {
        schema: pruneImagesConfigSchema,
        category: 'utility',
        description: 'Prunes unused Docker images to free disk space.',
        outputs: [],
    },
    'delete-image': {
        schema: deleteImageConfigSchema,
        category: 'utility',
        description: 'Deletes a specific Docker image.',
        consumesFromUpstream: ['imageId'],
        outputs: [],
    },
    'check-container-logs': {
        schema: checkContainerLogsConfigSchema,
        category: 'utility',
        description:
            'Searches container logs for a pattern and optionally fails the pipeline if not found.',
        consumesFromUpstream: ['containerId'],
        outputs: ['found', 'matchedLine'],
    },
    'cache-restore': {
        schema: cacheRestoreConfigSchema,
        category: 'utility',
        description: 'Restores a cached directory to speed up builds (e.g. node_modules).',
        outputs: ['cacheHit'],
    },
    'cache-save': {
        schema: cacheSaveConfigSchema,
        category: 'utility',
        description: 'Saves a directory to cache for future builds.',
        outputs: [],
    },
    'download-file': {
        schema: downloadFileConfigSchema,
        category: 'files',
        description: 'Downloads a file from a URL into the working directory.',
        outputs: ['filePath'],
    },
    'backup-volume-s3': {
        schema: backupVolumeS3ConfigSchema,
        category: 'files',
        description: 'Backs up a Docker volume to an S3-compatible bucket.',
        outputs: [],
    },
    'send-notification': {
        schema: sendNotificationConfigSchema,
        category: 'integration',
        description:
            'Sends a webhook notification (Slack, Discord, etc.) on success, failure, or always.',
        isEndNode: true,
        outputs: ['sent'],
    },
    'http-request': {
        schema: httpRequestConfigSchema,
        category: 'integration',
        description: 'Makes an HTTP request to an external API.',
        outputs: ['statusCode', 'body', 'headers'],
    },
    'update-commit-status': {
        schema: updateCommitStatusConfigSchema,
        category: 'integration',
        description: 'Updates the commit status on GitHub/GitLab (pending/success/failure).',
        outputs: [],
    },
    'git-tag': {
        schema: gitTagConfigSchema,
        category: 'integration',
        description: 'Creates a git tag on the current commit.',
        outputs: ['tagName'],
    },
    'create-release': {
        schema: createReleaseConfigSchema,
        category: 'integration',
        description: 'Creates a release on GitHub or GitLab.',
        outputs: ['releaseId', 'releaseUrl'],
    },
    'cherry-pick-commit': {
        schema: cherryPickCommitConfigSchema,
        category: 'integration',
        description: 'Cherry-picks a specific commit onto the current branch.',
        outputs: [],
    },
    'merge-branch': {
        schema: mergeBranchConfigSchema,
        category: 'integration',
        description: 'Merges a branch into the current branch.',
        outputs: [],
    },
    'trigger-stage-build': {
        schema: triggerStageBuildConfigSchema,
        category: 'deploy',
        description:
            'Triggers a new build on another deployment stage of the same repository. Only runs when the current pipeline has succeeded — use it to promote a successful pre-prod build to production. Place it at the end of the success path.',
        isEndNode: true,
        outputs: ['triggered', 'triggeredStageId', 'triggeredBuildId'],
    },
};
