-- AlterEnum
ALTER TYPE "DnsProviderType" ADD VALUE IF NOT EXISTS 'VULTR';
ALTER TYPE "DnsProviderType" ADD VALUE IF NOT EXISTS 'LINODE';
ALTER TYPE "DnsProviderType" ADD VALUE IF NOT EXISTS 'PORKBUN';
ALTER TYPE "DnsProviderType" ADD VALUE IF NOT EXISTS 'POWERDNS';
ALTER TYPE "DnsProviderType" ADD VALUE IF NOT EXISTS 'OVH';
