api:
  dashboard: true
  insecure: true

ping: { }

log:
  level: DEBUG
  format: json

accessLog:
  format: json

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http3: { }

  maintenance:
    address: ":8090"

experimental:
  plugins:
    staticresponse:
      moduleName: "github.com/jdel/staticresponse"
      version: "v0.0.1"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "nexploy_traefik_network_dev"
    watch: true

  file:
    directory: /etc/nexploy/traefik/service
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: letsencrypt@localhost.com
      storage: /etc/nexploy/traefik/service/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
